[package]
name = "prebuild"
version = "0.1.0"
edition = "2021"

[dependencies]
katex = "0.4"
walkdir = "2"
pulldown-cmark = "0.13"
toml = "1"
serde = { version = "1", features = ["derive"] }
imagesize = "0.15.0"
roxmltree = "0.21.1"
html-escape = "0.2.15"
gray_matter = { version = "0.3.2", default-features = false, features = ["toml"] }
usvg = { version = "0.48.1", default-features = false }

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
wildcard_imports = "allow"
uninlined_format_args = "allow"
similar_names = "allow"
too_many_lines = "allow"
many_single_char_names = "allow"
